[WIP] add fetch etc files
jsk-ros-pkg/jsk_robot pull request #1208
Opened 2020-02-27 05:15 UTC by sktometometo

- add upstart scripts and launch files which are usually in /etc/init/ and /etc/ros/indigo.
- add a script to deploy the upstart scripts
- modify the upstart scripts so that they will use jsk_fetch_startup version of launch files instead of robot.launch in /etc/ros/indigo

2020-02-27 07:56 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/launch/fetch.launch
> +  <arg name="rgb_camera_info_url" default="file:///etc/ros/indigo/depth_2019_12_11_03_27_26.yaml"/>
Oh, I totally forgot it but camera calibration file should be also a simulink

2020-09-18 06:50 UTC, knorth55 commented
@sktometometo I made a PR to update latest upstart scripts and fetch.launch.
please merge this PR and remove WIP label. https://github.com/sktometometo/jsk_robot/pull/1

2020-09-18 06:53 UTC, knorth55 commented
@sktometometo @708yamaguchi we can also replace `install_upstart.sh` script to this `deploy_upstart_script.sh`.
what do you think?

2020-09-18 06:59 UTC, sktometometo commented
@knorth55 which install_upstart.sh do you mean?

2020-09-18 07:48 UTC, knorth55 commented
@sktometometo this one https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_fetch_robot/jsk_fetch_startup/config/install_upstart.sh

2020-09-18 10:15 UTC, 708yamaguchi commented
@knorth55 

> we can also replace install_upstart.sh script to this deploy_upstart_script.sh. (or rename deploy_upstart_script.sh to install_upstart.sh)
> what do you think?

I think it's good idea to use `deploy_script.sh` because it is understandable than `install_upstart.sh`.

2020-10-29 19:33 UTC, knorth55 commented
@sktometometo please merge this pr https://github.com/sktometometo/jsk_robot/pull/2

2020-11-18 14:36 UTC, knorth55 commented
i rename from `deploy_upstart_scripts.sh` to `install_upstart.sh`

2021-09-25 07:43 UTC, k-okada reviewed
@sktometometo sorry, I merged #1328, so please fix conflicts

2021-09-25 12:09 UTC, knorth55 requested changes

2021-09-25 12:09 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/scripts/network_monitor.py
> +        "Script is expected to be run as an upstart job. If run manually, ">>>>>>> master
!!!!

2021-09-25 12:21 UTC, sktometometo commented on jsk_fetch_robot/jsk_fetch_startup/scripts/network_monitor.py
> +        "Script is expected to be run as an upstart job. If run manually, ">>>>>>> master
sorry for mistake.

2022-05-24 05:35 UTC, knorth55 approved these changes

2022-05-24 07:02 UTC, k-okada commented
@knorth55 if possible, please approve PR, after all CI is passed, so that I can push merge button, when I checked notification.

2022-05-24 07:02 UTC, merged

2022-05-24 07:40 UTC, knorth55 commented
@k-okada OK. I will.