Fix use torso
jsk-ros-pkg/jsk_robot pull request #1274
Opened 2020-11-18 07:17 UTC by softyanija

```
(send *ri* :angle-vector (send *fetch* :angle-vector) 3000 :use-torso t)
```
fails with 
```
Call Stack (max depth: 20):
  0: at (apply #'send-message self (class . super) :angle-vector av tm args)
  1: at (apply #'send-message self (class . super) :angle-vector av tm args)
  2: at (apply #'send-message self (class . super) :angle-vector av tm args)
  3: at (send-super* :angle-vector av tm args)
  4: at (let* ((prev-av (send self :state :potentio-vector :wait-until-update t)) (diff-av (v- av prev-av))) (when (send self :check-continuous-joint-move-over-180 diff-av) (let* (avs (minjerk (instance minjerk-interpolator :init)) (scale-av (send self :sub-angle-vector av prev-av)) dist div) (setq dist (abs (find-extream (coerce diff-av cons) #'abs #'>=))) (setq div (round (/ dist 120.0))) (send minjerk :reset :position-list (list prev-av (v+ prev-av scale-av)) :time-list (list tm)) (send minjerk :start-interpolation) (send minjerk :pass-time (/ tm div)) (dotimes (i div) (setq avs (append avs (list (send minjerk :pass-time (/ tm div)))))) (send* self :angle-vector-sequence-raw avs (make-list div :initial-element (/ tm div)) args) (return-from :angle-vector-raw (car (last avs))))) (send-super* :angle-vector av tm args))
  5: at (apply #'send self :angle-vector-raw av tm ctype start-time args)
  6: at (apply #'send self :angle-vector-raw av tm ctype start-time args)
  7: at (send* self :angle-vector-raw av tm ctype start-time args)
  8: at (return-from :angle-vector (send* self :angle-vector-raw av tm ctype start-time args))
  9: at (progn (return-from :angle-vector (send* self :angle-vector-raw av tm ctype start-time args)))
  10: at (if (send self :simulation-modep) (progn (return-from :angle-vector (send* self :angle-vector-raw av tm ctype start-time args))))
  11: at (when (send self :simulation-modep) (return-from :angle-vector (send* self :angle-vector-raw av tm ctype start-time args)))
  12: at (let ((ctype controller-type) (start-time 0) (start-offset-time nil) (use-torso t) (clear-velocities t)) (if (= (length args) 1) (setq ctype (car args) args (cdr args))) (if (and (>= (length args) 2) (null (member (car args) '(:use-torso :start-time :clear-velocities)))) (setq ctype (car args) start-time (cadr args) args (cddr args))) (if (member :use-torso args) (setq use-torso (cadr (member :use-torso args)))) (if (member :start-time args) (setq start-time (cadr (member :start-time args)))) (if (member :start-offset-time args) (setq start-offset-time (cadr (member :start-offset-time args)))) (if (member :clear-velocities args) (setq clear-velocities (cadr (member :clear-velocities args)))) (when (send self :simulation-modep) (return-from :angle-vector (send* self :angle-vector-raw av tm ctype start-time args))) (when (not (numberp tm)) (warn ":angle-vector tm is not a number, use :angle-vector av tm args")) (send* self :angle-vector-motion-plan av :ctype ctype :move-arm :rarm :total-time tm :start-offset-time (if start-offset-time start-offset-time start-time) :clear-velocities clear-velocities :use-torso use-torso args))
  13: at (send *ri* :angle-vector (send *fetch* :angle-vector) 4000 :use-torso nil)
  14: at (apply #'ros::load-org-for-ros ros::fullname args)
  15: at (apply #'ros::load-org-for-ros ros::fullname args)
  16: at (let ((ros::fullname fname)) (when (substringp "package://" fname) (setq ros::fullname (ros::resolve-ros-path fname)) (when ros::*compile-message* (let* ((ros::urlname (url-pathname fname)) (package-name (send ros::urlname :host)) (ros::path-name (format nil "~A_~A" package-name (substitute 95 47 (concatenate string (subseq (send ros::urlname :directory-string) 1) (send ros::urlname :name))))) (ros::old-module (find ros::path-name *loaded-modules* :key #'lisp::load-module-file-name :test #'equal))) (unless ros::old-module (let* ((ros::ppath (unix:getenv "CMAKE_PREFIX_PATH")) (dir (format nil "~A/share/roseus/ros/~A" (subseq ros::ppath 0 (position 58 ros::ppath)) package-name))) (unless (probe-file dir) (unix:mkdir dir)) (compiler:compile-file-if-src-newer ros::fullname (format nil "~A/~A" dir ros::path-name)) (return-from load (load (format nil "~A/~A.so" dir ros::path-name) :entry (format nil "___~A" ros::path-name)))))))) (if (null ros::fullname) (error "file ~s not found" fname)) (apply #'ros::load-org-for-ros ros::fullname args))
  17: at (load "amabe_hand_only.l")
  18: at #<compiled-code #X563d99089e18>
/opt/ros/melodic/share/euslisp/jskeus/eus/Linux64/bin/irteusgl 0 error: no such keyword :use-torso in (apply #'send-message self (class . super) :angle-vector av tm args)
```                                                                                                                
cc: @k-okada

2020-11-18 07:27 UTC, softyanija commented
11/4 には動いていた気がするんですが。。。

2020-11-18 07:47 UTC, knorth55 requested changes

2020-11-18 07:47 UTC, knorth55 commented on jsk_fetch_robot/fetcheus/fetch-interface.l
> +	 (setq args (append (subseq args 0 (position :use-torso args)) (if (> (length args) (+ 2 (position :use-torso args))) (subseq args (+ (position :use-torso args) 2))))))
please remove tab
```suggestion
     (setq args (append (subseq args 0 (position :use-torso args)) (if (> (length args) (+ 2 (position :use-torso args))) (subseq args (+ (position :use-torso args) 2))))))
```

2020-11-18 07:47 UTC, knorth55 commented on jsk_fetch_robot/fetcheus/fetch-interface.l
> +	(setq *co* (instance collision-object-publisher :init))
please remove tab
```suggestion
    (setq *co* (instance collision-object-publisher :init))
```

2020-11-18 07:49 UTC, knorth55 commented
元のコードを読むとわかりますが，実機では動きますが，kinematics simulatorでは前から動いてないと思います．

2020-11-18 07:58 UTC, knorth55 commented
このPRとは関係ないですが, `robot-interface :angle-vector`には positional argsがあるので，
癖として`(send *ri* :angle-vector (send *fetch* :angle-vector) 3000 nil 0 :use-torso)`という風に,
`:controller-type nil` と `start-time 0`をつけておいたほうがいいとおもいました．

2020-11-18 07:59 UTC, knorth55 commented
このPRを直しました．

https://github.com/softyanija/jsk_robot/pull/1

2020-11-18 11:05 UTC, knorth55 approved these changes

2020-11-20 12:27 UTC, knorth55 commented
@k-okada Travis passed! Can you merge this PR?

2020-11-20 13:56 UTC, merged