[jsk_pr2_moveit] compress point cloud
jsk-ros-pkg/jsk_robot pull request #1340
Opened 2021-05-30 12:16 UTC by shmpwk

With this PR,  use compressed point cloud to reduce the bandwidth in jsk_pr2_moveit.

2021-05-31 04:31 UTC, knorth55 commented
@shmpwk can you keep the current `start_pr2_moveit.launch` and make `start_pr2_moveit_remote.launch` for launching moveit in remote computer?

2021-05-31 04:51 UTC, shmpwk commented
OK, so like this?

2021-05-31 05:04 UTC, knorth55 commented
@shmpwk Yes, good! I also want to change the default `USE_KINECT:=true` in `start_pr2_moveit_remote.launch`.

2021-05-31 05:07 UTC, shmpwk commented
Done.

2021-05-31 05:11 UTC, knorth55 requested changes

2021-05-31 05:11 UTC, knorth55 commented on jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_moveit/start_pr2_moveit_remote.launch
> +  <arg name="USE_LASER_AND_KINECT" default="true" />
change this to `false`

2021-05-31 05:14 UTC, shmpwk commented on jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_moveit/start_pr2_moveit_remote.launch
> +  <arg name="USE_LASER_AND_KINECT" default="true" />
Sorry I forgot to change it.

2021-05-31 05:19 UTC, knorth55 commented on jsk_pr2_robot/jsk_pr2_startup/jsk_pr2_moveit/start_pr2_moveit_remote.launch
> +  <arg name="USE_LASER_AND_KINECT" default="true" />
Good!

2021-05-31 05:19 UTC, knorth55 approved these changes

2021-06-24 07:47 UTC, shmpwk commented
Travis says the build canceled and this is a change from the previous build, which failed. 
What is failed previous build?  Isn't only the last commit the target of the build?
The build log says nothing so I don't know how to fix it. Please give me a hint.

2021-07-16 09:52 UTC, merged