[baxtereus] support multiple coords for baxter ik
jsk-ros-pkg/jsk_robot pull request #1349
Opened 2021-06-17 11:20 UTC by knorth55

currently, baxter ik only supports sinlge target coordinates.
this PR supports multiple target coordinates.

2021-06-18 06:25 UTC, pazeshun requested changes

2021-06-18 06:25 UTC, pazeshun commented on jsk_baxter_robot/baxtereus/baxter-util.l
> +               (rotation-axis (if (listp current-coords) (make-list (length current-coords)) nil)))
```suggestion
       (let* ((move-target (cadr (memq :move-target args)))
              (current-coords (if (listp move-target)
                                (mapcar #'(lambda (x) (send x :copy-worldcoords)) move-target)
                                (send move-target :copy-worldcoords)))
              (rotation-axis (if (listp current-coords) (make-list (length current-coords)) nil)))
```

2021-06-18 06:25 UTC, pazeshun commented on jsk_baxter_robot/baxtereus/baxter-util.l
> +                                 (send move-target :copy-worldcoords))))
```suggestion
       (let* ((step 0.0)
              (move-target (cadr (memq :move-target args)))
              (current-coords (if (listp move-target)
                                (mapcar #'(lambda (x) (send x :copy-worldcoords)) move-target)
                                (send move-target :copy-worldcoords))))
```

2021-06-18 11:44 UTC, knorth55 commented
@pazeshun sorry, but I found another bug in `:link-list`. `:link-list` is also considered as single link list. but we can use multiple link lists for euslisp ik interface.
I fixed the issued in https://github.com/jsk-ros-pkg/jsk_robot/pull/1349/commits/ad5637b39dc250a6d08ba8b749d08ad3f76c8011

2021-06-22 12:32 UTC, pazeshun requested changes
Sorry for late.
Could you add new tests to https://github.com/jsk-ros-pkg/jsk_robot/blob/25ac99ab82539b0e95d20470db1675b5f2f58c56/jsk_baxter_robot/baxtereus/test/test-baxter.l?
Because I failed to find the issue about `:link-list` and lost confidence...

2021-06-23 04:13 UTC, knorth55 commented
@pazeshun thanks, I update this PR for adding the test.

2021-06-23 04:42 UTC, knorth55 commented
Now, I split the test code in #1351.
#1351 will fail the test, and this PR will pass the test.

2021-06-23 04:45 UTC, pazeshun requested changes

2021-06-23 04:45 UTC, pazeshun commented on jsk_baxter_robot/baxtereus/test/test-baxter.l
> +                    (send robot :link-list (send (send robot :larm :end-coords) :parent))
`(list (send robot :link-list (send (send robot :larm :end-coords) :parent)))`?

2021-06-23 04:45 UTC, pazeshun commented on jsk_baxter_robot/baxtereus/test/test-baxter.l
> +                    (send robot :link-list (send (send robot :rarm :end-coords) :parent))
`(list (send robot :link-list (send (send robot :rarm :end-coords) :parent)))`?

2021-06-23 04:51 UTC, pazeshun commented
At the time of #1177 , allowed test time of baxtereus is very limited, so adding many tests was unrealistic.
However, I think it is currently allowed because travis changed.
@knorth55 Is my understanding correct?

2021-06-23 04:59 UTC, knorth55 commented
@pazeshun thank you. I fixed the typo.
probably your understanding is correct.

2021-07-16 06:06 UTC, pazeshun approved these changes
Noetic test on github actions failed, but it has failed since #1354.

2021-07-17 02:33 UTC, merged