Publish /shutdown topic if go-to-kitchen demo fails
jsk-ros-pkg/jsk_robot pull request #1452
Opened 2022-04-20 12:09 UTC by 708yamaguchi

From https://github.com/knorth55/jsk_robot/pull/169
(I don't cherry-pick the first two commits, because these commits are already merged.)

With this PR, fetch shuts down itself when `go-to-kitchen` demo fails by timeout.

The purpose of this PR is to prevent fetch battery degradation.

2022-04-20 12:23 UTC, knorth55 commented
this PR depends on https://github.com/PR2/app_manager/pull/49.
Waiting for upstream.

2022-04-20 16:32 UTC, knorth55 requested changes

2022-04-20 16:32 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch.rosinstall.melodic
> +# after https://github.com/PR2/app_manager/pull/49 is merged
it is already merged

2022-04-20 16:32 UTC, knorth55 requested changes

2022-04-21 05:37 UTC, 708yamaguchi commented on jsk_fetch_robot/jsk_fetch.rosinstall.melodic
> +    version: fetch15
@knorth55 

Thank you for your review.

I updated `app_manager_utils` branch by cherry-pick (https://github.com/knorth55/jsk_robot/commit/c38f325eae6a2323ff6483be55bc9b54720f1e36)

I updated `app_manager` branch by cherry-pick (https://github.com/knorth55/jsk_robot/commit/a4957cbfb0710784593b570c155f680306c73d8a) and additional commit (https://github.com/jsk-ros-pkg/jsk_robot/pull/1452/commits/ea1a9b7dd5b081265c7958851b951794d26ded1c)

2022-04-21 06:43 UTC, 708yamaguchi commented
I rebased `origin/master` to resolve conflicts.

2022-04-25 13:07 UTC, merged