[jsk_naoqi_robot/README.md] update naoqi_dashboard branch info
jsk-ros-pkg/jsk_robot pull request #1542
Opened 2022-07-21 10:36 UTC by kochigami

Thanks to related issue1: https://github.com/k-okada/jsk_robot/issues/62#issuecomment-1185379536,
I modified `naoqi_dashboard` package as follows:
Related issue2: https://github.com/ros-naoqi/naoqi_dashboard/issues/5
Related PR: https://github.com/ros-naoqi/naoqi_dashboard/pull/6

(I confirmed this change works ubuntu 16.04 (kinetic) and 18.04 (melodic).)

So, I updated README.md of `jsk_naoqi_robot` to telling NAOqi users to use an updated branch.

@ayfujii @a-ichikura お時間ある時で大丈夫ですので、このドキュメントの記述でnaoqi_dashboardが動くか確認してくださるとありがたいです。（ROSのバージョンもお知らせしてくださるとありがたいです。）
（すみません、間違えてreviewボタンを押してしまいました・・・）

2022-07-22 12:37 UTC, k-okada commented
ところで，https://github.com/ros-naoqi/naoqi_dashboard/issues/5 のエラーが出る場合ですが，
```
 /usr/lib/python2.7/dist-packages/gobject/__init__.py
```
のファイルはあるでしょうか？無い場合
```
sudo apt install python-gobject-2
```
してから，naoqi_dashboard　を立ち上げても同じエラーになるでしょうか？

2022-07-27 04:59 UTC, kochigami commented
ありがとうございます。
 
> ところで，https://github.com/ros-naoqi/naoqi_dashboard/issues/5 のエラーが出る場合ですが，
> /usr/lib/python2.7/dist-packages/gobject/__init__.py
> 
> のファイルはあるでしょうか？

エラーが出たパソコンには、ありませんでした。

> 無い場合
> 
> sudo apt install python-gobject-2
> 
> してから，naoqi_dashboard　を立ち上げても同じエラーになるでしょうか？

同じエラーにならず、正常に立ち上がりました。
（Ubuntu 18.04, ROS melodicの環境で、
naoqi_dashboard (branch: [kochigami:modify-for-kinetic](https://github.com/kochigami/naoqi_dashboard/tree/modify-for-kinetic)) を使いました。）

どのようにnaoqi_dashboardを直せばよいでしょうか。

※ Ubuntu 16.04, ROS kineticの環境では、`/usr/lib/python2.7/dist-packages/gobject/__init__.py`がありました。
naoqi_dashboard (branch: [kochigami:modify-for-kinetic](https://github.com/kochigami/naoqi_dashboard/tree/modify-for-kinetic)) を使って動いています。）

2022-07-28 14:30 UTC, k-okada commented
https://github.com/ros/rosdistro/pull/33996
がマージされたら
https://github.com/ros-naoqi/naoqi_dashboard/blob/master/package.xml#L23 ?　に
`<run_depned>python-gobject</run_depend>` みたいに追加すると、‘rosdep install ... ` でインストールしてくれるようになると思います。

2022-08-09 10:07 UTC, k-okada requested changes
ありがとう https://github.com/k-okada/jsk_robot/tree/pepper_cross/jsk_naoqi_robot への差分に変更してPullRequest を更新してくれると助かります．

2022-08-15 07:59 UTC, kochigami commented
遅くなり申し訳ございません．

https://github.com/jsk-ros-pkg/jsk_robot/pull/1542#issuecomment-1192529540 を頂く前に，
kochigami-developにhttps://github.com/ros-naoqi/naoqi_dashboard/pull/6
の変更を反映してしまいましたので，まず削除しました．

```
kanae@kanae-ThinkPad-T480s:~/catkin_ws/src/naoqi_dashboard$ git log 
commit 33962f146c771272adc35ff216a519e5b113b66f
Merge: 116484f 6fed931
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Thu Jul 21 19:17:00 2022 +0900

    Merge pull request #6 from kochigami/modify-for-melodic
    
    [naoqi_dashboard/src/naoqi_dashboard/avahi.py] fix ImportError: No module named gobject (for ROS kinetic, melodic)

commit 6fed931934e8844deb9a6a9a2caf400ff227ca9a
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Thu Jul 21 16:00:18 2022 +0900

    [naoqi_dashboard/src/naoqi_dashboard/avahi.py] fix ImportError: No module named gobject (for ROS melodic)

commit 116484fc41bfe257779e517088630a7e29bc0e4c
Merge: 59272bd da1d014
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Fri Jun 7 13:54:19 2019 +0900

    Merge pull request #4 from kochigami/add-respawn-arg
    
    [naoqi_dashboard] add respawn=true arg to launch

commit da1d01422db58c7f1bf2d259ad0bb6ff41840f02
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Fri Jun 7 13:53:33 2019 +0900

    [naoqi_dashboard] add respawn=true arg to launch

commit 59272bd11380ec91966c743e326f12319b3a8def
Merge: 6da338a 2e0f90b
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Fri May 10 15:50:38 2019 +0900

    Merge pull request #1 from kochigami/update-network
    
    update aggregator yaml

commit 2e0f90b2f43ad1c246d17fc15edbab974ab90157
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Fri May 10 14:57:40 2019 +0900

    modify default launch_gui value: f -> t

commit e20b44f4921d2d5a110510cd7e2d8a8d26bbefdf
Merge: 232776a 1e7d987
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Mon May 6 16:10:02 2019 +0900

    Merge pull request #2 from kochigami/tmp-disable-dashboard
    
    [naoqi_dashboard] add gui arg
```

```
kanae@kanae-ThinkPad-T480s:~/catkin_ws/src/naoqi_dashboard$ git reset --hard HEAD^
HEAD is now at 116484f Merge pull request #4 from kochigami/add-respawn-arg
kanae@kanae-ThinkPad-T480s:~/catkin_ws/src/naoqi_dashboard$ git log 
commit 116484fc41bfe257779e517088630a7e29bc0e4c
Merge: 59272bd da1d014
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Fri Jun 7 13:54:19 2019 +0900

    Merge pull request #4 from kochigami/add-respawn-arg
    
    [naoqi_dashboard] add respawn=true arg to launch

commit da1d01422db58c7f1bf2d259ad0bb6ff41840f02
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Fri Jun 7 13:53:33 2019 +0900

    [naoqi_dashboard] add respawn=true arg to launch

commit 59272bd11380ec91966c743e326f12319b3a8def
Merge: 6da338a 2e0f90b
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Fri May 10 15:50:38 2019 +0900

    Merge pull request #1 from kochigami/update-network
    
    update aggregator yaml

commit 2e0f90b2f43ad1c246d17fc15edbab974ab90157
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Fri May 10 14:57:40 2019 +0900

    modify default launch_gui value: f -> t

commit e20b44f4921d2d5a110510cd7e2d8a8d26bbefdf
Merge: 232776a 1e7d987
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Mon May 6 16:10:02 2019 +0900

    Merge pull request #2 from kochigami/tmp-disable-dashboard
    
    [naoqi_dashboard] add gui arg

commit 1e7d9874964fc98ff22627dab2b00a878ef1d17d
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Mon May 6 14:44:27 2019 +0900

    [naoqi_dashboard] add gui arg

commit 232776aeb2fcfcecf26e0bc500e771165c5f4e63
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Thu May 2 15:11:12 2019 +0900

    update aggregator yaml

commit 6da338a9e7d4bcd7f5031146de293c89229d7ec6
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Thu Feb 28 19:37:16 2019 +0900
```

その上で，https://github.com/ros-naoqi/naoqi_dashboard/blob/master/package.xml#L23 に
`<run_depned>python-gobject</run_depend>`
を追加しました．
https://github.com/kochigami/naoqi_dashboard/commit/7f32005e08e0e76475af30263e77e6fb84f35060
```
kanae@kanae-ThinkPad-T480s:~/catkin_ws/src/naoqi_dashboard$ git log 
commit 7f32005e08e0e76475af30263e77e6fb84f35060
Author: Kanae Kochigami <kochigami@jsk.imi.i.u-tokyo.ac.jp>
Date:   Mon Aug 15 16:47:12 2022 +0900

    add run depend of python-gobject

commit 116484fc41bfe257779e517088630a7e29bc0e4c
Merge: 59272bd da1d014
Author: Kanae Kochigami <kochigami@users.noreply.github.com>
Date:   Fri Jun 7 13:54:19 2019 +0900

    Merge pull request #4 from kochigami/add-respawn-arg
    
    [naoqi_dashboard] add respawn=true arg to launch

commit da1d01422db58c7f1bf2d259ad0bb6ff41840f02
```

最後に，https://github.com/jsk-ros-pkg/jsk_robot/pull/1528 がマージされた後のjsk_naoqi_robot/README.md を見て，新たに追加しないといけないことはないことを確認しました．

2022-08-15 07:59 UTC, closed without merging