[jsk_robot_startup] Fix username retrieval in active_user.l
jsk-ros-pkg/jsk_robot pull request #1552
Opened 2022-08-02 06:10 UTC by sktometometo

Fix the problem reported in https://github.com/jsk-ros-pkg/jsk_robot/pull/1548.

2022-08-02 07:28 UTC, knorth55 commented
in `/etc/password`, the curent `active_user.l` uses `user description`.
this PR changes to use `username`.

For example, in my case, `Shingo Kitagawa` is parsed with current master,
but this PR changes to use `knorth55`.
```
knorth55:x:1000:1000:Shingo Kitagawa:/home/knorth55:/bin/bash

```

2022-08-04 05:54 UTC, k-okada commented
So prefeered behavir is 
- if we have null "user description", then use "user name" ?

2022-08-04 06:17 UTC, knorth55 commented
> So prefeered behavir is
if we have null "user description", then use "user name" ?

Yes, I think it is better.

2022-08-19 08:10 UTC, k-okada requested changes

2022-08-19 08:10 UTC, k-okada commented on jsk_robot_common/jsk_robot_startup/lifelog/active_user.l
> +    username
I think we should remove this generated file, `(unix::unlink "/tmp/username...")` ??  or use `(defun get-username () lisp::*user*)`

2022-08-19 08:10 UTC, k-okada commented on jsk_robot_common/jsk_robot_startup/lifelog/active_user.l
> +    )
please remove `/tmp/fullname_...` too

2022-08-24 07:57 UTC, sktometometo commented
Working on CI fixing

2022-08-24 09:15 UTC, k-okada commented
https://github.com/stack-of-tasks/eigenpy/pull/307 is blocker

2022-08-25 01:23 UTC, merged