[jsk_baxter_startup] update baxter.launch to support current baxter-jsk-softhand
jsk-ros-pkg/jsk_robot pull request #1564
Opened 2022-08-19 09:18 UTC by knorth55

this PR updated `baxter.launch` to support current baxter-jsk-softhand.

this PR supports:
- New grippers 
  - softhand
  - softhand-v2
- New cameras
  - Torso realsense
  - Kodak Spherical camera
  - Spherical stereo camera
- New microphone
  - Torso respeaker
- Launch xdisplay

You can run this launch with following commands.

### For Baxter + Default gripper

```bash
roslaunch jsk_baxter_startup baxter_default.launch
```

### For Baxter + Softhand gripper

```bash
roslaunch jsk_baxter_startup baxter_softhand.launch
```

2022-08-22 08:56 UTC, pazeshun requested changes
Please update https://github.com/jsk-ros-pkg/jsk_robot/blob/master/jsk_baxter_robot/jsk_baxter_startup/README.md

2022-08-22 09:14 UTC, knorth55 commented
@pazeshun thank you for your review. I update the readme.
https://github.com/knorth55/jsk_robot/blob/baxter-softhand-launch/jsk_baxter_robot/jsk_baxter_startup/README.md

2022-08-23 03:19 UTC, pazeshun requested changes
Sorry, but could you add when & how to use `jsk_baxter_udev/*` and `jsk_baxter_machine/env.sh` to README?
Or updating Baxer Instruction slide in JSK GoogleDrive is OK.

2022-08-23 03:28 UTC, pazeshun requested changes

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/baxter.launch
> +    <include file="$(find softhand_ros)/launch/softhand_left.launch"
Please add `softhand_ros` to package.xml

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/baxter_realsense_torso.launch
> +        pkg="jsk_interactive_marker" type="transformable_server_sample"
Please add `jsk_interactive_marker` to package.xml

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/baxter_realsense_torso.launch
> +        args="load jsk_pcl/ResizePointsPublisher $(arg realsense_camera_ns)/$(arg manager)">
Please add `jsk_pcl_ros` to package.xml

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/baxter_spherical_kodak.launch
> +  <node name="kodak_transform_publisher" pkg="tf" type="static_transform_publisher"
Please add `tf` to package.xml (although it is already required by `dynamic_tf_publisher`)

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/elp_usb.launch
> +    <node name="elp_camera_node" pkg="libuvc_camera" type="camera_node"
Please add `libuvc_camera` to package.xml

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/kodak_pixpro.launch
> +  <include file="$(find video_stream_opencv)/launch/camera.launch" >
Please add `video_stream_opencv` to package.xml

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/realsense.launch
> +  <include file="$(find realsense2_camera)/launch/rs_rgbd.launch">
Please add `realsense2_camera` to package.xml

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/realsense.launch
> +  <node name="depth_compress_republish" pkg="image_transport"
Please add `image_transport` to package.xml

2022-08-23 03:28 UTC, pazeshun commented on jsk_baxter_robot/jsk_baxter_startup/jsk_baxter_sensors/respeaker.launch
> +  <node name="respeaker_node" pkg="respeaker_ros" type="respeaker_node.py" respawn="true"/>
Please add `respeaker_ros` to package.xml

2022-08-23 08:45 UTC, knorth55 commented
Thanks, I updated the README and package.xml.

2022-08-25 03:40 UTC, pazeshun approved these changes

2022-08-25 03:50 UTC, merged