move update_workspace.sh to jsk_robot_startup and use it for pr2 and fetch
jsk-ros-pkg/jsk_robot pull request #1630
Opened 2022-09-30 07:32 UTC by knorth55

I move `update_workspace.sh` to `jsk_robot_startup` and use it for pr2 and fetch.

2022-09-30 10:05 UTC, sktometometo requested changes

2022-09-30 10:05 UTC, sktometometo commented on jsk_robot_common/jsk_robot_startup/scripts/update_workspace_main.sh
> +wstool update -t $WORKSPACE/src jsk-ros-pkg/jsk_robot
```suggestion
wstool update -t $WORKSPACE/src jsk-ros-pkg/jsk_robot --delete-changed-uris
```

2022-09-30 10:05 UTC, sktometometo commented on jsk_robot_common/jsk_robot_startup/scripts/update_workspace_main.sh
> +wstool update -t $WORKSPACE/src jsk-ros-pkg/jsk_robot
From https://github.com/knorth55/jsk_robot/pull/298

2022-09-30 10:10 UTC, sktometometo approved these changes

2022-10-29 09:01 UTC, tkmtnt7000 approved these changes

2023-06-20 03:18 UTC, tkmtnt7000 commented
Sorry, I mistakenly pushed. I've restored it.

2025-03-06 00:25 UTC, merged