add more info on mongodb
jsk-ros-pkg/jsk_robot pull request #1708
Opened 2022-10-28 11:09 UTC by k-okada

adbe52f1e (Kei Okada, 10 seconds ago)
    add information based on
    https://github.com/jsk-ros-pkg/jsk_robot/issues/1706

af53a852a (Kei Okada, 19 minutes ago)
    add example launch/script for mongo db

2022-10-28 13:47 UTC, mqcmd196 reviewed
I'll check it.
Minor fix
`robot_databse_monogo_example.py` -> `robot_database_mongo_example.py`

2022-11-04 05:49 UTC, tkmtnt7000 commented
With this change(4212b09fc796138096f96f36259d70751f1043e8), we can get pr1040 or fetch1075 existing smach database. This implementation is temporary, though.

2022-11-04 06:35 UTC, knorth55 commented
@tkmtnt7000 Super cool!

2022-11-08 05:45 UTC, mqcmd196 commented
@tkmtnt7000 which branch https://github.com/jsk-ros-pkg/jsk_robot/commit/4212b09fc796138096f96f36259d70751f1043e8 belongs to?

2022-11-08 06:10 UTC, tkmtnt7000 commented
Maybe https://github.com/tkmtnt7000/jsk_robot/tree/add_mongo_example_73B2

2022-12-15 02:03 UTC, mqcmd196 requested changes

2022-12-15 02:03 UTC, mqcmd196 commented on jsk_robot_common/jsk_robot_startup/scripts/robot_databse_mongo_example.py
> +        last_msg, _ = msg_store.query(
```python
last_msg = msg_store.query(
    SmachContainerStatus._type,
    {"active_states": "INIT"},
    single=True,
    sort_query=[("_meta.inserted_at", pymongo.DESCENDING)]
)
```

2022-12-15 02:03 UTC, mqcmd196 commented on jsk_robot_common/jsk_robot_startup/scripts/robot_databse_mongo_example.py
> +        msgs = msg_store.query(
```python
msgs = msg_store.query(
    SmachContainerStatus._type,
    {"header.stamp.secs": {"$gt": last_msg[0].header.stamp.secs}},
    sort_query=[("_meta.inserted_at", pymongo.ASCENDING)]
)
```

2022-12-15 02:03 UTC, mqcmd196 commented on jsk_robot_common/jsk_robot_startup/scripts/robot_databse_mongo_example.py
> +    key = 2
revert this pls

2022-12-15 02:04 UTC, mqcmd196 commented on jsk_robot_common/jsk_robot_startup/scripts/robot_databse_mongo_example.py
> +    key = 2
`key = 2`

2023-11-30 08:23 UTC, merged