[develop/fetch] Add nodes to adjust the volume of the speaking
jsk-ros-pkg/jsk_robot pull request #1746
Opened 2022-12-02 03:50 UTC by Kanazawanaoaki

`develop/fetch` version of https://github.com/jsk-ros-pkg/jsk_robot/pull/1715
This PR adds Apps to adjust the volume of Fetch `audible_warning` and `tweet`.

2022-12-02 05:44 UTC, mqcmd196 commented
Could you push only commits for Fetch? It seems it includes PR2's ones

2022-12-02 07:02 UTC, Kanazawanaoaki commented
Understood.
I have removed the changes not related to fetch.

2022-12-02 08:34 UTC, knorth55 requested changes

2022-12-02 08:34 UTC, knorth55 commented on jsk_fetch_robot/jsk_fetch_startup/apps/volume_zero/volume_zero.app
> +platform: fetch
we can use `platform: all`.
with that, we can move the app to `jsk_robot_startup` and use the same app for `fetch`, `pr2` and other robotcs.

2022-12-02 08:35 UTC, knorth55 commented
I also want to make an icon.
You can make an icon from free images.

2022-12-02 08:51 UTC, tkmtnt7000 commented
I'm not sure, but I have a little concern that it may be difficult to merge to master branch with icon made from いらすとや because of some policies...

2022-12-02 11:29 UTC, knorth55 commented
how about these ?
https://pixabay.com/images/search/mute%20sound/?manual_search=1

2022-12-02 17:38 UTC, Kanazawanaoaki commented
Thanks for the review and comments.  
As I mentioned in https://github.com/jsk-ros-pkg/jsk_robot/pull/1715#issuecomment-1334875994, I also thought it would be a good idea to put the app in `jsk_robot_startup` and create icons, so I'll work on it!

2022-12-03 10:02 UTC, Kanazawanaoaki commented
The icon image has been rebased as follows. This PR was rebased to resolve conflicts and tested with fetch15.  
| Volume lower | Volume reset | Volume zero |
| -- | -- | -- |
| ![volume_lower](https://user-images.githubusercontent.com/38127823/205435244-cd0d9f32-7a01-423e-aff7-a9c6994d245f.png) | ![volume_reset](https://user-images.githubusercontent.com/38127823/205435260-4678e140-3cf7-4972-8f61-05a80806f4e1.png) | ![volume_zero](https://user-images.githubusercontent.com/38127823/205435268-597c56c1-92ac-4102-8179-1f50fdd91474.png) |

2022-12-03 11:52 UTC, knorth55 approved these changes

2022-12-04 04:09 UTC, mqcmd196 approved these changes
LGTM

2022-12-04 04:29 UTC, merged